### ISSUE TITLE
[Q]: How do you build this?

### ISSUE THREAD

**Issue by dawikur** [rdebath/PuTTY#1]
Hi, I am looking around and still have no idea how to build it from sources. Can you help me with this?

**Comment by rdebath** [comment]
It depends a lot on what tools you are using to build with; If you're building for Linux you can just hit <code>make</code> in the putty-rdb branch. If you want to use Simon's <code>autoconf</code> setup the <code>mkauto.sh</code> will build that. For a Linux to Windows cross compile then <code>make windows-all</code> will build it (assuming the right dependencies are installed). Building using the Windows tools has an additional problem as you need to run the <code>mkfiles.pl</code> script using a perl interpreter to get the collection of makefiles that you can choose the right one. This can be run on Windows or Unix depending on where you have an interpreter.

The <code>mksrcarc.sh</code> should give me a zip file with the <code>mkfiles.pl</code> script already run (ie: with Windows Makefiles) would you like me to add that to my binary branch ?

**Comment by rdebath** [comment]
I've added a zip of the source (in CR/LF format with Makefiles) to the binaries branch.

**Comment by dawikur** [comment]
Thanks, I will try build it with you suggestions.
